# Generated by Django 4.2.30 on 2026-04-25 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lifestyle',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
