# Generated by Django 4.2.30 on 2026-04-29 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictions', '0002_lifestyle_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lifestyle',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='lifestyle',
            name='lifestyle_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
